# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hanasa/PythonProject/PyQt5/SimpleChat/res/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(800, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWidget.setWindowIcon(icon)
        self.Background = QtWidgets.QLabel(MainWidget)
        self.Background.setGeometry(QtCore.QRect(160, 0, 640, 480))
        self.Background.setStyleSheet("background-image: url(:/background/2.png);")
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.line = QtWidgets.QFrame(MainWidget)
        self.line.setGeometry(QtCore.QRect(160, 0, 3, 480))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ChatRoom = QtWidgets.QListWidget(MainWidget)
        self.ChatRoom.setGeometry(QtCore.QRect(0, 0, 160, 480))
        self.ChatRoom.setStyleSheet("background-color: rgb(36, 31, 49);")
        self.ChatRoom.setObjectName("ChatRoom")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/list_item_icons/chatting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.ChatRoom.addItem(item)
        self.InputBox = QtWidgets.QTextEdit(MainWidget)
        self.InputBox.setEnabled(True)
        self.InputBox.setGeometry(QtCore.QRect(180, 430, 501, 41))
        self.InputBox.setAutoFillBackground(False)
        self.InputBox.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:20px;\n"
"font: 14pt \"Ubuntu\";\n"
"color:rgb(255, 255, 255)")
        self.InputBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.InputBox.setObjectName("InputBox")
        self.SendButton = QtWidgets.QPushButton(MainWidget)
        self.SendButton.setGeometry(QtCore.QRect(700, 430, 81, 41))
        self.SendButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.SendButton.setMouseTracking(False)
        self.SendButton.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"border:2px solid rgb(35,35,35);\n"
"border-radius: 20px;\n"
"color:rgb(28, 113, 216)\n"
"")
        self.SendButton.setObjectName("SendButton")
        self.ChatArea = QtWidgets.QLabel(MainWidget)
        self.ChatArea.setGeometry(QtCore.QRect(160, 0, 640, 420))
        self.ChatArea.setText("")
        self.ChatArea.setObjectName("ChatArea")
        self.SettingButton = QtWidgets.QPushButton(MainWidget)
        self.SettingButton.setGeometry(QtCore.QRect(0, 440, 32, 32))
        self.SettingButton.setStyleSheet("border-radius:16px;\n"
"background-color: rgb(222, 221, 218);")
        self.SettingButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button_icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingButton.setIcon(icon2)
        self.SettingButton.setIconSize(QtCore.QSize(32, 32))
        self.SettingButton.setObjectName("SettingButton")

        self.retranslateUi(MainWidget)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        MainWidget.setWindowTitle(_translate("MainWidget", "SimpleChat"))
        __sortingEnabled = self.ChatRoom.isSortingEnabled()
        self.ChatRoom.setSortingEnabled(False)
        item = self.ChatRoom.item(0)
        item.setText(_translate("MainWidget", "聊天室01"))
        self.ChatRoom.setSortingEnabled(__sortingEnabled)
        self.InputBox.setHtml(_translate("MainWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SendButton.setText(_translate("MainWidget", "发送"))
import resource_rc
